### ISSUE TITLE
Refactor code to prevent duplicate tickets

### ISSUE THREAD

**Issue by milindl** [milindl/leaderboard#6]
Inside a single user X's `X.tickets.all`, there should be no repetition. In other words, the tuple (link, status) should not be the same. 

What this means is that the user should not be able to submit an identical link when a previous request with the same link is still pending. On the other hand, maybe we should not allow the same link at all. However, this is a bit tricky for competitive coding, where we may allow points based on the rank , which is on the same page so the link doesn't change. Alternatively, allowing the scoring to be based on various contest results (?) may work here.

Competetive coders, feel free to pitch in with ideas.

**Comment by APwhitehat** [comment]
@milindl this would stop new tickets from being added if there exists a pending ticket with the same link
`in app/models/ticket.rb`
`  validates_uniqueness_of :link, scope: [:user, :status]`

However I can't get the tests to work as expected, could you look into it?

**Comment by milindl** [comment]
This works for me. Maybe you're forgetting that each time before the test...do block, stuff is reset, so you need to call @ticket.save before creating a duplicate ticket.

PS: You also need to add database level uniqueness checks, so this is just step 1 in this bug.

**Comment by APwhitehat** [comment]
I figured out that I need to `@ticket.save`.
But when I `puts @user.tickets.all.inspect` the status always remains `"pending"` even if I
`@ticket.status = :approved` before `@ticket.save`.

I think I need to configure database level validation of some sort.(need to look this up)
